[theme]
name = "terminal"

[theme.custom]
panel_bg = "#121212"
sidebar_bg = "#0d0d0d"
active_row_bg = "#1e1e1e"
selection_bg = "#2a2a2a"
text = "#bebebe"
subtext0 = "#8a8a8d"
accent = "#e68e0d"
mauve = "#d35f5f"
green = "#ffc107"
blue = "#e68e0d"
red = "#d35f5f"
yellow = "#e68e0d"
