#!/usr/bin/env bash
# release-site-pr.sh — point the website at a published release: open a PR against GitHub `main`,
# merge it, and wait until noctraos.dev shows the new version. Cloudflare deploys the site by itself
# when GitHub `main` changes (wrangler.jsonc), so the merge IS the deploy.
#
#   scripts/release-site-pr.sh <build-dir>
#
# Uses <build-dir>/release/v<VERSION>/ for sizes, checksums and the torrent (scripts/update-site-release.py
# does the rewriting). Work happens in a fresh clone of GitHub main, never in the checkout it runs from.
#
# Needs: an authenticated `gh` and git push rights to GitHub, google-chrome for the social cards
# (Pillow is installed into a venv in <build-dir>; without Chrome the PR still opens, and says the cards were not redrawn).
# Environment: SITE_MERGE=auto (default: merge when GitHub allows it) | pr (open the PR and stop),
# GH_REPO (dazeb/noctraos), SITE_URL (https://noctraos.dev), SITE_WAIT_MIN (15).
set -Eeuo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
DIR="$(cd "${1:?usage: release-site-pr.sh <build-dir>}" && pwd)"
VERSION="$(tr -d '[:space:]' < "$ROOT/VERSION")"
TAG="v$VERSION"
REL="$DIR/release/$TAG"
GH_REPO="${GH_REPO:-dazeb/noctraos}"
SITE_URL="${SITE_URL:-https://noctraos.dev}"
BRANCH="release/$TAG-site"
log() { printf '=== %s %s\n' "$(date +%H:%M)" "$*"; }

[ -f "$REL/SHA256SUMS" ] || { echo "no built release at $REL" >&2; exit 1; }
# The public files must really be there before the site links to them.
curl -sSfI "https://dl.noctraos.dev/releases/$TAG/noctraos-$VERSION-amd64.iso" >/dev/null \
  || { echo "https://dl.noctraos.dev/releases/$TAG/ is not published yet: run iso/publish-release.sh first" >&2; exit 1; }

WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT
log "cloning GitHub main"
git clone -q --depth 1 "https://github.com/$GH_REPO.git" "$WORK/repo"
cd "$WORK/repo"
git remote set-url --push origin "git@github.com:$GH_REPO.git"
if [ "$(sed -n 's/.*"softwareVersion":"\([0-9.]*\)".*/\1/p' site/download.html | head -1)" = "$VERSION" ]; then
  echo "the site already shows $VERSION: nothing to do"; exit 0
fi
git checkout -q -B "$BRANCH"

log "updating the site files"
python3 scripts/update-site-release.py "$VERSION" "$REL" --root . --date "$(date -u +%F)"

CARDS="redrawn"
log "redrawing the social cards"
PYSOCIAL="$DIR/social-venv"   # Pillow, kept between releases
if ! { [ -x "$PYSOCIAL/bin/python" ] || { python3 -m venv "$PYSOCIAL" && "$PYSOCIAL/bin/pip" install -q pillow; }; } \
  || ! "$PYSOCIAL/bin/python" scripts/render-social.py og-home og-download x-launch x-proxmox; then
  CARDS="NOT redrawn (render-social.py failed on the build machine): run it by hand and push"
  git checkout -q -- site/img/social assets/promo/x 2>/dev/null || true
fi
git add -A
git -c user.name="noctraos release pipeline" -c user.email="admin@noctraos.dev" commit -q \
  -m "Release $VERSION: download page, torrent, Proxmox script, social cards

Written by scripts/update-site-release.py from the published files' sizes and SHA-256 sums.

Co-Authored-By: Claude Sonnet 5.5 <noreply@anthropic.com>"
git push -q --force-with-lease -u origin "$BRANCH"

BODY="Points the site at the published $TAG: ISO, VM disks, torrent, checksums, Proxmox script version.

Generated by the release pipeline from the files now on dl.noctraos.dev. Social cards: $CARDS.
Merging deploys the site (Cloudflare builds GitHub main)."
PR="$(gh pr list --repo "$GH_REPO" --head "$BRANCH" --json url --jq '.[0].url')"
[ -n "$PR" ] || PR="$(gh pr create --repo "$GH_REPO" --base main --head "$BRANCH" --title "Release $VERSION: website downloads" --body "$BODY")"
echo "PR: $PR"

if [ "${SITE_MERGE:-auto}" != auto ]; then echo "SITE_MERGE=${SITE_MERGE:-}: PR left open for review"; exit 0; fi
if ! gh pr merge "$PR" --squash --delete-branch; then
  echo "could not merge $PR (branch protection or a conflict): it is open for a human to merge" >&2; exit 1
fi

log "waiting for $SITE_URL/download to show $VERSION (Cloudflare deploys after the merge)"
end=$(( $(date +%s) + ${SITE_WAIT_MIN:-15} * 60 ))
until curl -sSf "$SITE_URL/download?v=$(date +%s)" | grep -q "\"softwareVersion\":\"$VERSION\""; do
  [ "$(date +%s)" -lt "$end" ] || { echo "merged, but $SITE_URL still does not show $VERSION after ${SITE_WAIT_MIN:-15} min: check the Cloudflare deployment" >&2; exit 1; }
  sleep 20
done
log "live: $SITE_URL/download shows $VERSION"
